
<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        spacing: 0
        padding: 0

        Button:
            id: btn
            on_release: playback.open(self)
            size_hint: (0.5, None)
            height: '30dp'

        Widget:
            on_parent: playback.dismiss()

        DropDown:
            id: playback
            on_select: btn.text = str(args[1][0])
#            on_select: print('Selected device: ' + str(args[1][1]))